# Change these first
owner: totavok8 # Your GitHub organization or username, where this repository lives
repo: uptime # The name of this repository

sites:
  - name: API Server 1
    url: https://api.kulik.uz/
  - name: API Server 2
    url: http://nossl_api.kulik.uz/
  - name: RU Server
    url: http://ru-link.kulik.uz/
  - name: CH Server
    url: https://cdn.kulik.uz/

#assignees: # Users to assign downtime issues (optional)
  #- shawnyeager

status-website:
  cname: status.kulik.uz
  favicon: https://raw.githubusercontent.com/chdtv/uptime/master/logo.png
  baseUrl: /
  logoUrl: https://raw.githubusercontent.com/chdtv/uptime/master/logo.png
  name: CHD-TV
  introTitle: "**CHD-TV** status"
  introMessage: This is a status page which uses **real-time** data from our servers
  navbar:
    - title: Status
      href: /
i18n:
  footer: '[https://t.me/chdiptv](https://t.me/chdiptv)'
  incidentViewOnGitHub: ''
